name: ALP Portal unit tests (Frontend)

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  test-alp-portal-frontend:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_NOTEBOOK_BASE }}
            ${{ secrets.SSH_PRIVATE_KEY_STARBOARD_WRAP }}

    - uses: dorny/paths-filter@v2
      id: check_file_changed
      with:
        filters: |
          portal_fe_changed:
            - 'apps/portal/**'

    - name: Setup node if files have changed
      uses: actions/setup-node@v4
      if: steps.check_file_changed.outputs.portal_fe_changed == 'true'
      with:
        node-version: '18.14.0'

    # Run the step only with "portal_fe_changed" equals "True"
    - name: Run unit tests if files have changed
      if: steps.check_file_changed.outputs.portal_fe_changed == 'true'
      run: |
        cd libs/portal-plugin
        yarn --prefer-offline
        cd ../portal-components
        yarn --prefer-offline
        yarn build
        cd ../../apps/portal
        yarn --prefer-offline
        yarn test
