name: Build Docker Image

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop

# Run only one job per branch
concurrency:
  group: ${{ github.head_ref || github.ref_name }}-docker-ui-ci # per branch build
  cancel-in-progress: ${{ (github.head_ref || github.ref_name) != 'develop' }} # except for develop branch

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  bld:
    environment: development
    runs-on:
      group: dockerup
    if: github.ref_name == 'develop' || github.event_name == 'workflow_dispatch' || contains('release', ${{ github.head_ref || github.ref_name }}) || ( github.event_name == 'pull_request' && !github.event.pull_request.draft ) # runs if PR is not draft /or/ workflow_dispatch /or/ release branch
    strategy:
      matrix:
        include:
          - name: alp-data-node/alp-caddy
            directory: .
            context: .
            fileName: Dockerfile
            platforms: linux/amd64

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ vars.GHA_BUILD_DEBUG != 'true' }}
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - uses: actions/checkout@v4

      - name: Get docker tag name
        id: docker_tag
        shell: bash
        run: |
          echo BRANCH_NAME=$BRANCH_NAME
          if [ $BRANCH_NAME = "develop" ]; then
            echo "is_push=true" >> $GITHUB_OUTPUT
          elif [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
            echo "is_push=true" >> $GITHUB_OUTPUT
          else
            echo "is_push=false" >> $GITHUB_OUTPUT
          fi

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_STARBOARD_WRAP }}
            ${{ secrets.SSH_PRIVATE_KEY_NOTEBOOK_BASE }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Collect Git and SSH config files in a directory that is part of the Docker build context
        run: |
          cp -r ~/.gitconfig  ~/.ssh .github/
          cd .github/
          sed 's|/home/runner|/root|g' -i.bak .ssh/config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ vars.DOCKER_BUILD_DISABLE != 'true' }}
        id: build_push
        continue-on-error: false
        with:
          builder: ${{ steps.builder.outputs.name }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # ulimit: nofile=1048576:1048576
          platforms: ${{ matrix.platforms || 'linux/amd64,linux/arm64' }}
          context: ${{ matrix.context }}
          file: ${{ matrix.directory }}/${{ matrix.fileName }}
          push: ${{ steps.docker_tag.outputs.is_push }}
          tags: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io/${{ matrix.name }}:${{ env.BRANCH_NAME }},${{ vars.AZ_REGISTRY_NAME }}.azurecr.io/${{ matrix.name }}:${{ github.sha }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          build-args: |
            docker_image_prefix=${{ vars.AZ_REGISTRY_NAME }}.azurecr.io
            GIT_COMMIT_ARG=${{ github.sha }}

      - name: Prune tagged images
        if: ${{ github.head_ref || github.ref_name }} == 'develop' || github.event_name == 'workflow_dispatch' || DOCKER_BUILD_DISABLE
        shell: bash
        env:
          AZ_REGISTRY_NAME: ${{ vars.AZ_REGISTRY_NAME }}
          AZ_REGISTRY_PASSWORD: ${{ secrets.AZ_REGISTRY_PASSWORD }}
          AZ_REGISTRY_PRUNE_ENABLE_TAGGED: ${{ vars.AZ_REGISTRY_PRUNE_ENABLE_TAGGED }}
          AZ_REGISTRY_PRUNE_DAYS_TAGGED: ${{ vars.AZ_REGISTRY_PRUNE_DAYS_TAGGED }}
          AZ_REGISTRY_REPOSITORY: ${{ matrix.name }}
          AZ_REGISTRY_USERNAME: ${{ secrets.AZ_REGISTRY_USERNAME }}
          AZ_REGISTRY_WHITELIST_REGEX: ${{ vars.AZ_REGISTRY_WHITELIST_REGEX }}
        run: |
          if [ ${AZ_REGISTRY_PRUNE_DAYS_TAGGED:-20} = 0 ]; then
            AZ_REGISTRY_PRUNE_TIMESTAMP=$(date -u -Is)
          else
            TODAY=$(date +%Y-%m-%d)
            AZ_REGISTRY_PRUNE_TIMESTAMP="$(date -d "$TODAY - ${AZ_REGISTRY_PRUNE_DAYS_TAGGED:-20} days" +%Y-%m-%d)"
          fi
          echo AZ_REGISTRY_PRUNE_TIMESTAMP=$AZ_REGISTRY_PRUNE_TIMESTAMP

          echo ". 1 - GET manifest metadata -  deprecated warning is not relevant"
          az acr manifest metadata list --name ${AZ_REGISTRY_REPOSITORY} --registry ${AZ_REGISTRY_NAME} --username "${AZ_REGISTRY_USERNAME}" --password "${AZ_REGISTRY_PASSWORD}" --orderby time_asc --query "[?lastUpdateTime < '${AZ_REGISTRY_PRUNE_TIMESTAMP}' && not_null(tags)]" > private.json
          wc -l private.json

          echo ". 2 - ANALYZE each tag as deletable True/False - show first 20"
          cat private.json | yq -rP 'map({"digest":.digest, "tags":(.tags|@json),"count":(.tags|length),"lengths":([.tags[]|length]|@json),"deletable":(.tags|map(test(env(AZ_REGISTRY_WHITELIST_REGEX))|not)|@json)})' | tee private1-analysis.yml | yq '.[0:20]'

          echo ". 3 - ACTION lock manifests with deletable False i.e. tags matching RegEx"
          cat private1-analysis.yml | yq 'map(select(.deletable|contains("false")).digest) | .[1]' | xargs -I% az acr repository update -u ${AZ_REGISTRY_USERNAME} -p ${AZ_REGISTRY_PASSWORD} --name ${AZ_REGISTRY_NAME} --image ${AZ_REGISTRY_REPOSITORY}@% --delete-enabled false --write-enabled true | yq -P

          echo ". 4 - SELECT images to be deleted i.e. manifests excepting deletable False i.e. tags not matching RegEx"
          cat private1-analysis.yml | yq 'map(select(.deletable|contains("false")|not))' > private2-todelete.yml
          echo . INFO for deletion - BranchNames
          cat private2-todelete.yml | yq -P 'map(select(.lengths!="[40]") | .tags | @jsond)'
          echo . INFO for deletion - single tag commitIds
          cat private2-todelete.yml | yq -P 'map(select(.lengths=="[40]") | .tags | @jsond)'

          if [ "${AZ_REGISTRY_PRUNE_ENABLE_TAGGED}" = true ]; then
            echo ". 5 - ACTION delete tagged digests ..."
            yq '.[].digest' private2-todelete.yml | sort -u | xargs -I% az acr repository delete -u ${AZ_REGISTRY_USERNAME} -p ${AZ_REGISTRY_PASSWORD} --name ${AZ_REGISTRY_NAME} --image ${AZ_REGISTRY_REPOSITORY}@% --yes
          else
            echo ". 5 - SKIPPED delete digests ..."
          fi

      - name: Prune untagged images
        shell: bash
        if: always()
        env:
          AZ_REGISTRY_NAME: ${{ vars.AZ_REGISTRY_NAME }}
          AZ_REGISTRY_PASSWORD: ${{ secrets.AZ_REGISTRY_PASSWORD }}
          AZ_REGISTRY_PRUNE_ENABLE_UNTAGGED: ${{ vars.AZ_REGISTRY_PRUNE_ENABLE_UNTAGGED }}
          AZ_REGISTRY_PRUNE_DAYS_UNTAGGED: ${{ vars.AZ_REGISTRY_PRUNE_DAYS_UNTAGGED }}
          AZ_REGISTRY_REPOSITORY: ${{ matrix.name }}
          AZ_REGISTRY_USERNAME: ${{ secrets.AZ_REGISTRY_USERNAME }}
          AZ_REGISTRY_WHITELIST_REGEX: ${{ vars.AZ_REGISTRY_WHITELIST_REGEX }}
        run: |
          if [ ${AZ_REGISTRY_PRUNE_DAYS_UNTAGGED:-1} = 0 ]; then
            AZ_REGISTRY_PRUNE_TIMESTAMP=$(date -u -Is)
          else
            TODAY=$(date +%Y-%m-%d)
            AZ_REGISTRY_PRUNE_TIMESTAMP="$(date -d "$TODAY - ${AZ_REGISTRY_PRUNE_DAYS_UNTAGGED:-1} days" +%Y-%m-%d)"
          fi
          echo AZ_REGISTRY_PRUNE_TIMESTAMP=$AZ_REGISTRY_PRUNE_TIMESTAMP

          echo . INFO for deletion - untagged
          az acr manifest metadata list --registry ${AZ_REGISTRY_NAME} --name ${AZ_REGISTRY_REPOSITORY} --username "${AZ_REGISTRY_USERNAME}" --password "${AZ_REGISTRY_PASSWORD}" --orderby time_asc --query "[?lastUpdateTime < '${AZ_REGISTRY_PRUNE_TIMESTAMP}' && tags[0]==null].digest" -o tsv | tee private.tsv

          if [ "${AZ_REGISTRY_PRUNE_ENABLE_UNTAGGED}" = true ]; then
            echo ". ACTION delete untagged digests ..."
            cat private.tsv | xargs -I% az acr repository delete -n ${AZ_REGISTRY_NAME} --username "${AZ_REGISTRY_USERNAME}" --password "${AZ_REGISTRY_PASSWORD}" -t ${AZ_REGISTRY_REPOSITORY}@% -y || true
          else
            echo ". 5 - SKIPPED delete digests ..."
          fi
