name: build plugin

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
      - trex

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY_NOTEBOOK_BASE }}
              ${{ secrets.SSH_PRIVATE_KEY_STARBOARD_WRAP }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alp-os'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Build
        run: yarn
        env:
         CI: false
      - name: Pack
        run: yarn pack
        env:
         CI: false
      # - name: Push
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: alp-os-d2e-ui-v1.0.0.tgz
      #     tag: trex-latest
      #     target_commit: trex
      #     prerelease: true
      #     overwrite: true
      - name: Delete Package
        run: 'curl -L -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/alp-os/packages/npm/d2e-ui'
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}