name: build plugin

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
      - trex

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY_NOTEBOOK_BASE }}
              ${{ secrets.SSH_PRIVATE_KEY_STARBOARD_WRAP }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alp-os'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >>~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          brew --version
      - name: Build
        run: yarn
        env:
         CI: false
      - name: Patch Package
        run: jq '.private=false' package.json > tmppkg; mv tmppkg package.json
      - name: Update version
        run: jq --arg v "-$(date +%s)-$GITHUB_SHA" '.version+=$v' package.json > tmppkg; mv tmppkg package.json
      - name: Publish
        run: yarn publish
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'd2e-ui'
          package-type: 'npm'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: 'true'
      # - name: Pack
      #   run: yarn pack --ignore-scripts
      #   env:
      #    CI: false
      # - name: Push
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: alp-os-d2e-ui-v1.0.0.tgz
      #     tag: trex-latest
      #     target_commit: trex
      #     prerelease: true
      #     overwrite: true
