name: SonarCloud Scan

on:
  workflow_dispatch:
  # # Trigger analysis when pushing in master or pull requests, and when creating
  # # a pull request.
  # push:
  #   branches:
  #   - development
  # pull_request:
  #   types: [opened, ready_for_review, reopened, synchronize]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}